### ISSUE TITLE
Integration broken since Home Assistant 2023.6

### ISSUE THREAD

**Issue by fodi666** [ecoen66/cisco_imc#1]
Hi,
I've been using this integration with my C240 M4 server and was working fine and I really liked it. However, since updating to 2023.6 the integration cannot be loaded due to some errors. Might be because of the Python version change?
Could you please look into it? Unfortunately I have no expertise with Python or Home Assistant addons.
Thanks

Here is the log (I am currently on 2023.7):
```
Logger: homeassistant.setup
Source: custom_components/cisco_imc/imc_device.py:8
Integration: Cisco IMC ([documentation](https://github.com/ecoen66/cisco_imc), [issues](https://github.com/ecoen66/cisco_imc/issues))
First occurred: 17 July 2023 at 15:11:34 (1 occurrences)
Last logged: 17 July 2023 at 15:11:34

Setup failed for custom integration cisco_imc: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/cisco_imc/__init__.py", line 27, in <module>
    from .switch import ImcPollingSwitch
  File "/config/custom_components/cisco_imc/switch.py", line 11, in <module>
    from .imc_device import CiscoImcDevice
  File "/config/custom_components/cisco_imc/imc_device.py", line 8, in <module>
    from homeassistant.helpers.entity_registry import async_get_registry
ImportError: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

**Comment by ecoen66** [comment]
@fodi666 I have been too busy with my day job lately.  However, I just spent some time fixing this for my own HA setup.  Try the latest update.

**Comment by fodi666** [comment]
Thanks for fixing it, now it works again.
